language: python
python:
  - "3.4"
  - "3.5"
# save pip installs between runs
cache: "pip"

# services
services:
  - memcached
  - redis-server
# command to install dependencies
install: "pip install --upgrade pip setuptools && pip install -r requirements/test.txt && pip install -r flaskserver/requirements.txt && pip install -r service1/requirements.txt"
script: "./runtests.sh"
