language: python
python:
  - "3.4"
  - "3.5"
# save pip installs between runs
cache: "pip"

# services
services:
  - memcached
  - redis-server
# command to install dependencies
install: "pip install -r requirements/test.txt"
script: "./runtests.sh"
