"""empty message

Revision ID: 20dfe0b98eb4
Revises: None
Create Date: 2015-09-13 00:44:39.760260

"""

# revision identifiers, used by Alembic.
revision = '20dfe0b98eb4'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtags',
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.text'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], )
    )
    op.drop_table('tags')
    op.drop_table('results')
    op.add_column('status', sa.Column('in_reply_to', sa.Integer(), nullable=True))
    op.add_column('status', sa.Column('t_id', sa.Integer(), nullable=True))
    op.add_column('status', sa.Column('text', sa.String(), nullable=True))
    op.add_column('status', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'status', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'status', 'status', ['in_reply_to'], ['id'])
    op.drop_column('status', 'favorited')
    op.add_column('user', sa.Column('tracking', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tracking')
    op.add_column('status', sa.Column('favorited', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.drop_constraint(None, 'status', type_='foreignkey')
    op.drop_column('status', 'user_id')
    op.drop_column('status', 'text')
    op.drop_column('status', 't_id')
    op.drop_column('status', 'in_reply_to')
    op.create_table('results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('result_all', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('result_no_stop_words', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'results_pkey')
    )
    op.create_table('tags',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['status'], [u'status.id'], name=u'tags_status_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'tags_pkey')
    )
    op.drop_table('hashtags')
    ### end Alembic commands ###
